connection.driver_class=org.postgresql.Driver
connection.url=jdbc:postgresql://localhost:5432/SmartGym
connection.username=SmartGym
connection.password=SmartGym

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.connection.provider_class=org.hibernate.hikaricp.internal.HikariCPConnectionProvider

hikari.maximumPoolSize=10
hikari.minimumIdle=2
hikari.connectionTimeout=30000

telegram.bot.token=8777106934:AAEl5AedL_6WvDH_bQuXN6BheUWM1fHty6U
telegram.bot.name= TrainingAndNutrition

SerializationFeature.WRITE_DATES_AS_TIMESTAMPS=false
DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES=false

API_KEY=m7tYKQuRlWTcAYhr0aTQ4w==uIawz2eLmzZaisVd
BASE_URL=https://api.calorieninjas.com/v1/nutrition?query=




